### ISSUE TITLE
[WinError 32] The process cannot access the file under Temp directory

### ISSUE THREAD

**Issue by salihcaan** [eyalev/print-dict#1]
**Environment**: Windows 10, Anaconda, Python 3.7.4

**Problem**: When printing a dictionary, ```from param_dict import pd``` tries to access temporary file but the following error raises: 
```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\hasan\Anaconda3\lib\site-packages\print_dict\print_dict.py", line 16, in pd
  File "C:\Users\hasan\Anaconda3\lib\site-packages\print_dict\print_dict.py", line 12, in print_dict
    print(format_dict(arg))
  File "C:\Users\hasan\Anaconda3\lib\site-packages\print_dict\print_dict.py", line 43, in format_dict
    os.unlink(temp_file.name)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\hasan\\AppData\\Local\\Temp\\tmpqbkx_krj'```

**Comment by squeezer44** [comment]
Environment: Windows 10, Python 3.8.2, print-dict 0.1.11

Same for me when I'm doing this:

```
from print_dict import pd as print_dict


class Object1:
    pass


class Object2:

    def __repr__(self):
        return "<Object2 info>"


def custom_method():
    pass


object1 = Object1()


data = {
    "one": "value-one",
    "two": "value-two",
    "three": "value-three",
    "four": {
        '1': '1', '2': '2', '3': [1, 2, 3, 4, 5], '4': {
            'method': custom_method,
            'tuple': (1, 2),
            'unicode': u'\u2713',
            'ten': 'value-ten',
            'eleven': 'value-eleven',
            '3': [1, 2, 3, 4]
        }
    },
    "object1": object1,
    "object2": Object2(),
    "class": Object1

}

print_dict(data)
```

**Comment by eyalev** [comment]
@salihcaan @squeezer44 thanks for the report!. I updated the repo. Please update (`pip install -U print-dict`) and let me know if it works.
