### ISSUE TITLE
`print-dict` is not compatible with Python 3.13

### ISSUE THREAD

**Issue by m472** [eyalev/print-dict#3]
Installing `print_dict` under Python 3.13 leads to the following error:
```raw
Traceback (most recent call last):
  File "<python-input-0>", line 1, in <module>
    import print_dict
  File "/home/matz/.conda/envs/python313/lib/python3.13/site-packages/print_dict/__init__.py", line 2, in <module>
    from .print_dict import print_dict, pd, format_dict
  File "/home/matz/.conda/envs/python313/lib/python3.13/site-packages/print_dict/print_dict.py", line 8, in <module>
    from yapf.yapflib.yapf_api import FormatCode
  File "/home/matz/.conda/envs/python313/lib/python3.13/site-packages/yapf/__init__.py", line 35, in <module>
    from lib2to3.pgen2 import tokenize
ModuleNotFoundError: No module named 'lib2to3'
```
This is because the standard library module `lib2to3` was removed in Python 3.13 but is required by `yapf` version 30.

**Comment by m472** [comment]
overwriting the `yapf` version in the requirements using `pip install --upgrade yapf` seems to solve the issue
